/**
 * WD4 · Compile authored markdown packs into a typed TS module.
 *
 * esbuild builds the server bundle with `--bundle --packages=external`. A
 * runtime `readFileSync` against `import.meta.url` would not resolve correctly
 * post-bundle. This script reads the markdown files at build time and emits
 * `server/lib/domainContext/generatedPacks.ts`, which esbuild bundles natively.
 *
 * Run via: `npm run build:domain-packs` (auto-invoked by `npm run dev` and
 * `npm run build`).
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { discoverPacks } from "../lib/domainContext/discoverPacks.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const PACKS_DIR = join(HERE, "..", "lib", "domainContext", "packs");
const OUTPUT_FILE = join(HERE, "..", "lib", "domainContext", "generatedPacks.ts");

function escapeForTemplate(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function main(): void {
  const { packs, errors } = discoverPacks(PACKS_DIR);
  if (errors.length) {
    console.warn(`build-domain-packs: ${errors.length} pack(s) failed to parse:`);
    for (const e of errors) console.warn(`  - ${e.file}: ${e.reason}`);
  }
  if (!packs.length) {
    console.warn("build-domain-packs: 0 packs discovered — emitting empty module");
  }

  const lines: string[] = [
    "// AUTO-GENERATED by scripts/build-domain-packs.ts. Do not edit by hand.",
    "// Source files: server/lib/domainContext/packs/*.md",
    "",
    'import type { DomainPack } from "./types.js";',
    "",
    "export const PACKS: ReadonlyArray<DomainPack> = [",
  ];
  for (const p of packs) {
    lines.push("  {");
    lines.push(`    id: ${JSON.stringify(p.id)},`);
    lines.push(`    title: ${JSON.stringify(p.title)},`);
    lines.push(`    category: ${JSON.stringify(p.category)},`);
    lines.push(`    priority: ${p.priority},`);
    lines.push(`    enabledByDefault: ${p.enabledByDefault},`);
    lines.push(`    version: ${JSON.stringify(p.version)},`);
    lines.push(`    approxTokens: ${p.approxTokens},`);
    lines.push(`    body: \`${escapeForTemplate(p.body)}\`,`);
    lines.push("  },");
  }
  lines.push("];");
  lines.push("");

  writeFileSync(OUTPUT_FILE, lines.join("\n"), "utf8");
  const totalTokens = packs.reduce((s, p) => s + p.approxTokens, 0);
  console.log(
    `build-domain-packs: wrote ${packs.length} pack(s), ~${totalTokens} tokens → ${OUTPUT_FILE}`
  );
}

main();
