/**
 * Wave CS4 · Symbol → file:line index (the "where is X defined" lookup).
 *
 * Cold-start initiative Piece 4. Walks every tracked, non-test .ts/.tsx file
 * (via `git ls-files`, which respects .gitignore and avoids the glob-recursion
 * under-count gotcha) and records each top-level `export` definition as one TSV
 * row: symbol, kind, file, line. Collapses "where is X" from a grep returning
 * 4–43 mixed mentions (definition + imports + comments + tests) plus manual
 * triage into a single `grep` over one file with exactly one row per export.
 *
 * Tests are EXCLUDED on purpose — test-file hits were the dominant grep noise.
 *
 * FRESHNESS TIER = warn, not block. Line numbers move on almost every edit, so
 * a hard CI diff-gate would fail unrelated PRs. Instead this is regenerated at
 * each /wave-commit (fresh for the next session) and CI warns (continue-on-error)
 * if it drifts. If a line looks off, the file column is still correct — grep the
 * symbol within that one file. (The hard-gated, can't-drift index is the
 * registries manifest; symbols are the best-effort tier.)
 */
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, "..", "..");
const OUT_REL = "docs/index/symbols.generated.tsv";

const EXPORT_RE =
  /^export\s+(?:default\s+)?(?:abstract\s+)?(?:async\s+)?(const|let|var|function|class|interface|type|enum)\s+([A-Za-z_$][\w$]*)/;

function isTestFile(path: string): boolean {
  return (
    path.includes("/tests/") ||
    /\.test\.[tj]sx?$/.test(path) ||
    /\.spec\.[tj]sx?$/.test(path) ||
    path.includes(".vitest.")
  );
}

interface Row {
  symbol: string;
  kind: string;
  file: string;
  line: number;
}

function trackedSourceFiles(): string[] {
  const out = execSync("git ls-files -- '*.ts' '*.tsx'", { cwd: REPO_ROOT, encoding: "utf8" });
  return out
    .split("\n")
    .filter(Boolean)
    .filter((f) => !f.endsWith(".d.ts") && !isTestFile(f));
}

export function collectSymbols(): Row[] {
  const rows: Row[] = [];
  for (const file of trackedSourceFiles()) {
    let text: string;
    try {
      text = readFileSync(join(REPO_ROOT, file), "utf8");
    } catch {
      continue;
    }
    const lines = text.split("\n");
    for (let i = 0; i < lines.length; i++) {
      const m = lines[i]!.match(EXPORT_RE);
      if (m) rows.push({ symbol: m[2]!, kind: m[1]!, file, line: i + 1 });
    }
  }
  rows.sort((a, b) => a.symbol.localeCompare(b.symbol) || a.file.localeCompare(b.file));
  return rows;
}

function render(rows: Row[]): string {
  const head = [
    "# AUTO-GENERATED by server/scripts/generate-symbols.ts. Do not edit by hand.",
    "# Regenerate: npm --prefix server run gen:symbols (runs at /wave-commit).",
    "# Top-level exports only; tests excluded. Lines best-effort — if stale, grep the symbol in the file column.",
    "# columns: symbol\tkind\tfile\tline",
  ];
  const body = rows.map((r) => `${r.symbol}\t${r.kind}\t${r.file}\t${r.line}`);
  return [...head, ...body, ""].join("\n");
}

function main(): void {
  const rows = collectSymbols();
  const outAbs = join(REPO_ROOT, OUT_REL);
  mkdirSync(dirname(outAbs), { recursive: true });
  writeFileSync(outAbs, render(rows), "utf8");
  console.log(`generate-symbols: wrote ${OUT_REL} (${rows.length} exported symbols)`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
